spring:
  application:
    name: school
  datasource:
#    platform: postgres
   #url: ${URL_DATABASE:jdbc:postgresql://192.168.0.159:5432/school_db}
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5432/school_db}
    username: postgres
    password: n
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    port: ${RABBITMQ_PORT:5672}

server:
  port: 8080

key: ABCDabcd1234